import { isSupabaseConfigured, supabase } from "./supabase";

export const NICKNAME_MIN_LENGTH = 2;
export const NICKNAME_MAX_LENGTH = 12;

/** 한글, 영문, 숫자, _, . */
export const NICKNAME_PATTERN = /^[a-zA-Z0-9_.\uAC00-\uD7A3\u1100-\u11FF\u3130-\u318F]+$/;

export function validateNicknameFormat(
  nickname: string,
): { ok: true; value: string } | { ok: false; error: string } {
  const trimmed = nickname.trim();

  if (trimmed.length < NICKNAME_MIN_LENGTH || trimmed.length > NICKNAME_MAX_LENGTH) {
    return {
      ok: false,
      error: `닉네임은 ${NICKNAME_MIN_LENGTH}~${NICKNAME_MAX_LENGTH}자로 입력해 주세요.`,
    };
  }

  if (!NICKNAME_PATTERN.test(trimmed)) {
    return {
      ok: false,
      error: "한글, 영문, 숫자, _, . 만 사용할 수 있어요.",
    };
  }

  return { ok: true, value: trimmed };
}

export function filterNicknameInput(value: string): string {
  return value
    .replace(/[^a-zA-Z0-9_.\uAC00-\uD7A3\u1100-\u11FF\u3130-\u318F]/g, "")
    .slice(0, NICKNAME_MAX_LENGTH);
}

export async function isNicknameTaken(
  nickname: string,
  excludeUserId?: string,
): Promise<boolean> {
  if (!isSupabaseConfigured()) return false;

  const { data, error } = await supabase
    .from("profiles")
    .select("id")
    .ilike("nickname", nickname.trim())
    .maybeSingle();

  if (error || !data) return false;
  if (excludeUserId && data.id === excludeUserId) return false;
  return true;
}

export function isAutoGeneratedNickname(nickname: string, email?: string | null): boolean {
  if (!email) return false;
  const local = email.split("@")[0]?.trim().toLowerCase();
  if (!local) return false;
  return nickname.trim().toLowerCase() === local;
}
