-- ═══════════════════════════════════════════════════════════
-- DEPRECATED PATH — use gift-transfer.sql
-- ═══════════════════════════════════════════════════════════
-- Supabase SQL Editor에서는 `\i` 가 동작하지 않습니다.
-- 아래와 동일하게 **supabase/gift-transfer.sql** 파일 전체를
-- 복사해 SQL Editor에 붙여 넣고 실행하세요.
--
-- 이 파일은 예전 문서/스크립트 호환을 위해 남겨 두었습니다.
-- 실제 RPC 정의는 gift-transfer.sql 에만 유지합니다.
